In [41]:
import numpy as np
import pandas as pd
import math
np.set_printoptions(precision=2)

In [86]:
x_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

print(f"x_train: {x_train.shape}, y_train: {y_train.shape}")

x_train: (3, 4), y_train: (3,)


In [87]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])

In [88]:
def predict(x, w, b):
    n = x.shape[0]
    f_wb = 0

    for i in range(n):
        f_wb += w[i] * x[i]

    f_wb += b
    return f_wb

In [89]:
predict(x_train[0], w_init, b_init)

459.9999976194083

In [90]:
def compute_cost(x, y, w, b):
    m = x.shape[0]
    cost = 0

    # 1/2m sum (w.x + b - y)^2
    for i in range(m):
        cost += (np.dot(w, x[i]) + b - y[i]) ** 2
    cost = 1/(2 * m) * cost
    return cost

In [91]:
cost = compute_cost(x_train, y_train, w_init, b_init)
print(f'Cost at optimal w : {cost}')

Cost at optimal w : 1.5578904428966628e-12


In [92]:
print(x_train,"\n\n" ,y_train)

[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]] 

 [460 232 178]


In [99]:
def compute_gradient(x, y, w, b):
    # x -> (m, n)
    # y -> (n,)
    # w -> (n,)
    # b -> scaler

    m,n = x.shape
    dj_dw = np.zeros((n,))
    dj_db = 0.

    for i in range(m):
        error =  (np.dot(w , x[i]) + b) - y[i]
        for j in range(n):
            dj_dw[j] += error * x[i,j]
        dj_db += error

    dj_dw /= m
    dj_db /= m

    
    return dj_dw, dj_db


dj_dw = [-2.73e-03 -6.27e-06 -2.22e-06 -6.92e-05]
dj_db = -1.6739251501955248e-06


In [101]:
dj_dw, dj_db = compute_gradient(x_train, y_train, w_init, b_init)

print(f"dj_dw = {dj_dw}")
print(f"dj_db = {dj_db}")

dj_dw = [-2.73e-03 -6.27e-06 -2.22e-06 -6.92e-05]
dj_db = -1.6739251501955248e-06


In [125]:
def gradient_descent(x, y, w, b, alpha, nums_iters):
    prev_w = []
    prev_b = 0

    for i in range(nums_iters):

        dj_dw, dj_db = compute_gradient(x, y, w, b)

        w -= alpha * dj_dw
        b -= alpha * dj_db

        if i != 0 and np.equal(prev_w, w).all() and prev_b == b:
            print("found early")
            return w, b
        else:
            prev_w = w
            prev_b = b
        
    return w, b


In [204]:
# initialize parameters
initial_w = np.array([  0.16 , 23.19, -64.88,   1.78]  )
initial_b = 1.27

In [203]:

# some gradient descent settings
iterations = 1_000_000
alpha = 8.36e-7
# run gradient descent 
initial_w, initial_b = gradient_descent(x_train, y_train, initial_w, initial_b, alpha, iterations)
print(f"b,w found by gradient descent: {initial_b:0.2f},{initial_w} ")
m,_ = x_train.shape
for i in range(m):
    print(f"prediction: {np.dot(x_train[i], initial_w) + initial_b:0.2f}, target value: {y_train[i]}")

b,w found by gradient descent: 1.28,[  0.16  23.28 -65.14   1.8 ] 
prediction: 459.83, target value: 460
prediction: 232.40, target value: 232
prediction: 177.77, target value: 178


# Standard Deviation

In [55]:
def standard_deviation(x , sample=False):
    n = x.shape[0]
    
    mean = np.sum(x) / n

    if sample:
        n -= 1

    varience = np.sum((x - mean)**2) / n
    std = math.sqrt(varience)

    print(f"Mean = {mean}")
    print(f"Varience = {varience}")
    print(f"Standard Daviation = {std}")

    return std
    

In [56]:
# generating randome data
test_data = np.random.random_sample((10))

# ranging the data from 0-10
test_data = test_data*10
print(test_data)


[0.45 1.93 4.78 9.54 0.38 6.54 1.67 7.28 7.92 7.89]


In [58]:
std = standard_deviation(test_data, sample=True)

Mean = 4.838408682780785
Varience = 11.93303318562321
Standard Daviation = 3.454422265100665
